In [ ]:

from google.colab import files
 
 
uploaded = files.upload()

Saving bill_authentication.csv to bill_authentication.csv


In [ ]:

import pandas as pd
import io
import numpy as np
 
bankdata = pd.read_csv(io.BytesIO(uploaded['bill_authentication.csv']))
print(bankdata)

      Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]


In [ ]:
X = bankdata.drop('Class', axis=1)
y = bankdata['Class']



In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier

In [ ]:
X_train, X_rem, y_train, y_rem = train_test_split(X,y, train_size=0.7)

In [ ]:
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=0.5)


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X_train_standardized = scaler.fit_transform(X_train)
X_test_standardized = scaler.fit_transform(X_test)
X_valid_standardized = scaler.fit_transform(X_valid)

print(X_train_standardized)
print(type(X_train_standardized))
#print(type(y_train))

[[ 0.16210156  0.23539191 -1.35131461 -1.21033266]
 [ 0.25259651  1.19849289 -0.78851409  0.02788152]
 [ 1.08052602  0.81010467 -0.58450472  0.38435785]
 ...
 [ 1.07256823  0.84127131 -0.55019669  0.21859436]
 [-0.86213304  0.21102999 -0.62018599 -0.6731772 ]
 [ 1.27694834 -1.10854804  0.80057111  1.11905987]]
<class 'numpy.ndarray'>


In [ ]:
from sklearn import svm
svc = svm.SVC(kernel= 'linear', random_state=1, C=1.0)
svc.fit(X_train_standardized,y_train)

SVC(kernel='linear', random_state=1)

In [ ]:
y_val_predictions = svc.predict(X_valid_standardized)


In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_valid, y_val_predictions))

Accuracy: 0.9854368932038835


In [ ]:
from sklearn.metrics import f1_score

In [ ]:
print("f1 score:",f1_score(y_valid, y_val_predictions))

f1 score: 0.9832402234636871


In [ ]:
#0 means authentic and 1 means counterfeit 
#True Negative False positive] [ False Negative True Positive
from sklearn.metrics import classification_report, confusion_matrix
cm = confusion_matrix(y_valid,y_val_predictions)
print(cm)
print("true negative:",cm[0][0])
print("false positive:",cm[0][1])
print("false negative:",cm[1][0])
print("true positive:",cm[1][1])
print(classification_report(y_valid,y_val_predictions))

[[115   3]
 [  0  88]]
true negative: 115
false positive: 3
false negative: 0
true positive: 88
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       118
           1       0.97      1.00      0.98        88

    accuracy                           0.99       206
   macro avg       0.98      0.99      0.99       206
weighted avg       0.99      0.99      0.99       206



In [ ]:
# part 2: here ill test the c value to be 1.25
from sklearn import svm
tuned_svc = svm.SVC(kernel= 'linear', random_state=1, C=1.25)
tuned_svc.fit(X_train_standardized,y_train)

SVC(C=1.25, kernel='linear', random_state=1)

In [ ]:
new_y_val_predictions = tuned_svc.predict(X_valid_standardized)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_valid, new_y_val_predictions))

Accuracy: 0.9854368932038835


In [ ]:
print("f1 score:",f1_score(y_valid, new_y_val_predictions))

f1 score: 0.9832402234636871


In [ ]:
#0 means authentic and 1 means counterfeit 
#True Negative False positive] [ False Negative True Positive
from sklearn.metrics import classification_report, confusion_matrix
cm = confusion_matrix(y_valid,new_y_val_predictions)
print(cm)
print("true negative:",cm[0][0])
print("false positive:",cm[0][1])
print("false negative:",cm[1][0])
print("true positive:",cm[1][1])
print(classification_report(y_valid,new_y_val_predictions))

[[115   3]
 [  0  88]]
true negative: 115
false positive: 3
false negative: 0
true positive: 88
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       118
           1       0.97      1.00      0.98        88

    accuracy                           0.99       206
   macro avg       0.98      0.99      0.99       206
weighted avg       0.99      0.99      0.99       206



In [ ]:
#knn algorithm
from scipy.stats import mode

def euclidean_distance(pt1, pt2):
  distance = np.sqrt(np.sum(pt1-pt2)**2)

  return distance



def knn(x_train_set, x_development_set, y_train_data, k_value ):
  
  y_hat = []

  for x_valid_point in x_development_set:

    distances = []


    for x_train_point in range(len(x_train_set)):
      euc_distance = euclidean_distance(np.array(x_train_set[x_train_point,:]),x_valid_point)
      distances.append(euc_distance)
    distances = np.array(distances)

    sorted_distances = np.argsort(distances)[:k_value]
    labels = y[sorted_distances]

    lab = mode(labels)
    lab = lab.mode[0]
    y_hat.append(lab)

  return y_hat





In [ ]:
k_values = (2,3,4,5,6,7,8,9,10,11,12)

for k_value in k_values:
  y_predicted_knn = knn(X_train_standardized,X_valid_standardized,y_train,k_value)
  scratchKNNAccuracy = metrics.accuracy_score(y_valid, y_predicted_knn)

  print("The k value is k = %d is %f" %(k_value, scratchKNNAccuracy ))


The k value is k = 2 is 0.577670
The k value is k = 3 is 0.592233
The k value is k = 4 is 0.572816
The k value is k = 5 is 0.567961
The k value is k = 6 is 0.582524
The k value is k = 7 is 0.567961
The k value is k = 8 is 0.582524
The k value is k = 9 is 0.563107
The k value is k = 10 is 0.582524
The k value is k = 11 is 0.567961
The k value is k = 12 is 0.572816


In [ ]:
# Part 4: Use Dummy Classifier from sklearn on the data.

# The Dummy classifier uses most frequent strategy
classifer_most_frequent = DummyClassifier(strategy = 'most_frequent').fit(X_train_standardized, y_train)
y_predictions_for_frequency = classifer_most_frequent.predict(X_valid_standardized)
accuracy_for_most_frequent = metrics.accuracy_score(y_valid, y_predictions_for_frequency)
print ("The accuracy score using strategy = most_frequent is %f " %accuracy_for_most_frequent)

# The Dummy classifier uses stratified strategy
classifier_stratified = DummyClassifier(strategy = 'stratified').fit(X_train_standardized, y_train)
y_strat_prediction = classifier_stratified.predict(X_valid_standardized)
accuracy_for_stratified = metrics.accuracy_score(y_valid, y_strat_prediction)
print ("The accuracy score using strategy = stratified is %f " %accuracy_for_stratified)

The accuracy score using strategy = most_frequent is 0.524272 
The accuracy score using strategy = stratified is 0.461165 


In [ ]:
#part 5: comparison of svm vs KNN and baseline 

#SVM with tuned hyperparmaters with a c=1.25
tuned_svc = svm.SVC(kernel= 'linear', random_state=1, C=1.25)
tuned_svc.fit(X_train_standardized,y_train)

new_y_val_predictions = tuned_svc.predict(X_valid_standardized)

# Model Accuracy
print("Accuracy:",metrics.accuracy_score(y_valid, new_y_val_predictions))
print("f1 score:",f1_score(y_valid, new_y_val_predictions))


#KNN with k=6
y_predicted_knn = knn(X_train_standardized,X_test_standardized,y_train,6)
scratchKNNAccuracy = metrics.accuracy_score(y_valid, y_predicted_knn)
print("The k value is k = %d is %f" %(k_value, scratchKNNAccuracy ))


#baseline classifier with most frequent strategy
y_predictions_for_frequency = classifer_most_frequent.predict(X_test_standardized)
accuracy_for_most_frequent = metrics.accuracy_score(y_test, y_predictions_for_frequency)
print ("The accuracy score using strategy = most_frequent is %f " %accuracy_for_most_frequent)

#baseline classifier with stratified strategy
y_strat_prediction = classifier_stratified.predict(X_test_standardized)
accuracy_for_stratified = metrics.accuracy_score(y_test, y_strat_prediction)
print ("The accuracy score using strategy = stratified is %f " %accuracy_for_stratified)





Accuracy: 1.0
f1 score: 1.0
The k value is k = 12 is 0.524272
The accuracy score using strategy = most_frequent is 0.640777 
The accuracy score using strategy = stratified is 0.558252 
